-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
--data.image = love.graphics.newImage(path.."cell.sprite.png")
--data.image:setFilter("nearest", "nearest")
data.textureName = "cell.sprite.png"
data.animations = {
	icon_link={
		[0]={u=1668, v=121, w=83, h=83, offsetX=41, offsetY=40, duration=0.0333333},
		[1]={u=1748, v=0, w=83, h=83, offsetX=41, offsetY=40, duration=0.0333333},
		[2]={u=1864, v=0, w=83, h=83, offsetX=41, offsetY=40, duration=0.0333333},
		[3]={u=1947, v=0, w=83, h=83, offsetX=41, offsetY=40, duration=0.0333333},
		[4]={u=1947, v=83, w=83, h=83, offsetX=41, offsetY=40, duration=0.0666667},
		[5]={u=1947, v=0, w=83, h=83, offsetX=41, offsetY=40, duration=0.0333333},
		[6]={u=1864, v=0, w=83, h=83, offsetX=41, offsetY=40, duration=0.0333333},
		[7]={u=1748, v=0, w=83, h=83, offsetX=41, offsetY=40, duration=0.0333333},
		scale=1
	},
	trail={
		[0]={u=252, v=846, w=22, h=22, offsetX=11, offsetY=11, duration=0.0333333},
		scale=1
	},
	head={
		[0]={u=375, v=667, w=156, h=163, offsetX=71, offsetY=69, duration=0.0333333},
		[1]={u=375, v=352, w=156, h=163, offsetX=71, offsetY=69, duration=0.0333333},
		[2]={u=488, v=172, w=156, h=163, offsetX=71, offsetY=69, duration=0.0333333},
		scale=1
	},
	head_glow={
		[0]={u=440, v=0, w=222, h=172, offsetX=112, offsetY=80, duration=0.0666667},
		[1]={u=1396, v=849, w=214, h=70, offsetX=108, offsetY=-4, duration=0.0666667},
		[2]={u=440, v=0, w=222, h=172, offsetX=112, offsetY=80, duration=0.0666667},
		scale=1
	},
	port={
		[0]={u=0, v=872, w=106, h=105, offsetX=54, offsetY=54, duration=0.0333333},
		scale=1
	},
	port_glow={
		[0]={u=733, v=492, w=133, h=132, offsetX=75, offsetY=48, duration=0.0333333},
		scale=1
	},
	flesheater={
		[0]={u=994, v=0, w=66, h=93, offsetX=33, offsetY=43, duration=0.0666667},
		[1]={u=1272, v=924, w=66, h=93, offsetX=33, offsetY=43, duration=0.0666667},
		[2]={u=1441, v=919, w=66, h=93, offsetX=33, offsetY=43, duration=0.0666667},
		scale=1
	},
	flesheater_glow={
		[0]={u=1343, v=921, w=98, h=102, offsetX=49, offsetY=47, duration=0.0666667},
		[1]={u=1574, v=919, w=98, h=102, offsetX=49, offsetY=47, duration=0.0666667},
		[2]={u=1343, v=921, w=98, h=102, offsetX=49, offsetY=47, duration=0.0666667},
		scale=1
	},
	body={
		[0]={u=184, v=670, w=161, h=176, offsetX=80, offsetY=86, duration=0.0666667},
		[1]={u=306, v=846, w=161, h=176, offsetX=80, offsetY=86, duration=0.0666667},
		[2]={u=279, v=0, w=161, h=176, offsetX=80, offsetY=86, duration=0.0666667},
		scale=1
	},
	body_glow={
		[0]={u=994, v=944, w=204, h=78, offsetX=101, offsetY=27, duration=0.0666667},
		[1]={u=1613, v=846, w=202, h=68, offsetX=101, offsetY=26, duration=0.0666667},
		[2]={u=279, v=176, w=209, h=176, offsetX=103, offsetY=86, duration=0.0666667},
		scale=1
	},
	gun={
		[0]={u=1748, v=914, w=58, h=110, offsetX=27, offsetY=80, duration=0.0666667},
		[1]={u=0, v=0, w=108, h=226, offsetX=53, offsetY=139, duration=0.0666667},
		[2]={u=0, v=226, w=108, h=226, offsetX=53, offsetY=139, duration=0.0666667},
		[3]={u=467, v=868, w=70, h=156, offsetX=34, offsetY=126, duration=0.0666667},
		[4]={u=248, v=872, w=58, h=140, offsetX=27, offsetY=110, duration=0.0666667},
		[5]={u=1748, v=914, w=58, h=110, offsetX=27, offsetY=80, duration=0.0666667},
		scale=1
	},
	gun_idle={
		[0]={u=1748, v=914, w=58, h=110, offsetX=28, offsetY=80, duration=0.0666667},
		scale=1
	},
	gun_bounce_idle={
		[0]={u=1672, v=914, w=58, h=110, offsetX=30, offsetY=82, duration=0.0666667},
		scale=1
	},
	gun_bounce_fire={
		[0]={u=1672, v=914, w=58, h=110, offsetX=30, offsetY=82, duration=0.0666667},
		[1]={u=537, v=862, w=86, h=162, offsetX=44, offsetY=132, duration=0.0666667},
		[2]={u=0, v=452, w=108, h=226, offsetX=55, offsetY=140, duration=0.0666667},
		[3]={u=279, v=352, w=96, h=166, offsetX=52, offsetY=136, duration=0.0666667},
		[4]={u=108, v=537, w=58, h=138, offsetX=30, offsetY=110, duration=0.0666667},
		[5]={u=1806, v=914, w=58, h=110, offsetX=30, offsetY=82, duration=0.0666667},
		scale=1
	},
	bullet_glow={
		[0]={u=751, v=948, w=76, h=76, offsetX=38, offsetY=36, duration=0.0666667},
		[1]={u=1198, v=944, w=74, h=74, offsetX=37, offsetY=35, duration=0.0666667},
		[2]={u=901, v=944, w=78, h=80, offsetX=39, offsetY=39, duration=0.0666667},
		[3]={u=827, v=948, w=74, h=76, offsetX=36, offsetY=35, duration=0.0666667},
		scale=1
	},
	bullet={
		[0]={u=0, v=977, w=32, h=32, offsetX=16, offsetY=16, duration=0.0666667},
		[1]={u=490, v=830, w=32, h=32, offsetX=16, offsetY=16, duration=0.0666667},
		[2]={u=522, v=830, w=32, h=32, offsetX=16, offsetY=16, duration=0.0666667},
		[3]={u=554, v=808, w=32, h=32, offsetX=16, offsetY=16, duration=0.0666667},
		scale=1
	},
	bullet_bounce={
		[0]={u=32, v=977, w=68, h=16, offsetX=34, offsetY=8, duration=0.0666667},
		[1]={u=32, v=993, w=68, h=16, offsetX=34, offsetY=8, duration=0.0666667},
		[2]={u=279, v=518, w=68, h=16, offsetX=34, offsetY=8, duration=0.0666667},
		[3]={u=32, v=993, w=68, h=16, offsetX=34, offsetY=8, duration=0.0666667},
		scale=1
	},
	body_bullet={
		[0]={u=467, v=846, w=23, h=22, offsetX=12, offsetY=11, duration=0.0666667},
		[1]={u=184, v=846, w=22, h=22, offsetX=12, offsetY=11, duration=0.0666667},
		[2]={u=206, v=846, w=23, h=22, offsetX=12, offsetY=11, duration=0.0666667},
		[3]={u=229, v=846, w=23, h=22, offsetX=12, offsetY=11, duration=0.0666667},
		scale=1
	},
	spikey={
		[0]={u=1533, v=160, w=135, h=121, offsetX=67, offsetY=60, duration=0.0666667},
		[1]={u=1613, v=0, w=135, h=121, offsetX=67, offsetY=60, duration=0.0666667},
		[2]={u=1396, v=728, w=135, h=121, offsetX=67, offsetY=60, duration=0.0666667},
		[3]={u=1478, v=604, w=135, h=121, offsetX=67, offsetY=60, duration=0.0666667},
		[4]={u=1531, v=725, w=135, h=121, offsetX=67, offsetY=60, duration=0.0666667},
		[5]={u=1478, v=604, w=135, h=121, offsetX=67, offsetY=60, duration=0.133333},
		[6]={u=1396, v=728, w=135, h=121, offsetX=67, offsetY=60, duration=0.0666667},
		[7]={u=1613, v=0, w=135, h=121, offsetX=67, offsetY=60, duration=0.0666667},
		scale=1
	},
	spikey_glow={
		[0]={u=108, v=872, w=140, h=142, offsetX=70, offsetY=69, duration=0.0666667},
		scale=1
	},
	heart={
		[0]={u=166, v=537, w=88, h=133, offsetX=43, offsetY=65, duration=0.0666667},
		[1]={u=254, v=537, w=88, h=133, offsetX=43, offsetY=65, duration=0.0666667},
		[2]={u=342, v=534, w=88, h=133, offsetX=43, offsetY=65, duration=0.0666667},
		[3]={u=430, v=515, w=88, h=133, offsetX=43, offsetY=65, duration=0.0666667},
		[4]={u=518, v=515, w=88, h=133, offsetX=43, offsetY=65, duration=0.0666667},
		[5]={u=606, v=495, w=88, h=133, offsetX=43, offsetY=65, duration=0.0666667},
		scale=1
	},
	heart_glow={
		[0]={u=1283, v=764, w=113, h=157, offsetX=56, offsetY=77, duration=0.0666667},
		scale=1
	},
	body_grey={
		[0]={u=108, v=0, w=171, h=179, offsetX=86, offsetY=86, duration=0.0666667},
		[1]={u=108, v=179, w=171, h=179, offsetX=86, offsetY=86, duration=0.0666667},
		[2]={u=108, v=358, w=171, h=179, offsetX=86, offsetY=86, duration=0.0666667},
		scale=1
	},
	body_grey_glow={
		[0]={u=0, v=678, w=184, h=194, offsetX=92, offsetY=92, duration=0.0666667},
		scale=1
	},
	repair={
		[0]={u=866, v=480, w=140, h=124, offsetX=69, offsetY=61, duration=0.0666667},
		[1]={u=1483, v=444, w=130, h=116, offsetX=68, offsetY=58, duration=0.0666667},
		[2]={u=1063, v=480, w=140, h=124, offsetX=69, offsetY=61, duration=0.0666667},
		[3]={u=1203, v=480, w=140, h=124, offsetX=69, offsetY=61, duration=0.0666667},
		[4]={u=1338, v=604, w=140, h=124, offsetX=69, offsetY=61, duration=0.0666667},
		[5]={u=1343, v=480, w=140, h=124, offsetX=69, offsetY=61, duration=0.0666667},
		[6]={u=1574, v=281, w=130, h=116, offsetX=68, offsetY=58, duration=0.0666667},
		[7]={u=1063, v=480, w=140, h=124, offsetX=69, offsetY=61, duration=0.0666667},
		[8]={u=1434, v=320, w=140, h=124, offsetX=69, offsetY=61, duration=0.0666667},
		scale=1
	},
	reactor0={
		[0]={u=1503, v=0, w=110, h=160, offsetX=56, offsetY=78, duration=0.0333333},
		scale=1
	},
	reactor1={
		[0]={u=733, v=788, w=110, h=160, offsetX=57, offsetY=76, duration=0.0666667},
		[1]={u=751, v=624, w=110, h=160, offsetX=57, offsetY=76, duration=0.0666667},
		[2]={u=843, v=784, w=110, h=160, offsetX=57, offsetY=76, duration=0.0666667},
		[3]={u=861, v=624, w=110, h=160, offsetX=57, offsetY=76, duration=0.0666667},
		[4]={u=843, v=784, w=110, h=160, offsetX=57, offsetY=76, duration=0.0666667},
		[5]={u=751, v=624, w=110, h=160, offsetX=57, offsetY=76, duration=0.0666667},
		scale=1
	},
	reactor2={
		[0]={u=1313, v=160, w=110, h=160, offsetX=55, offsetY=77, duration=0.0666667},
		[1]={u=1393, v=0, w=110, h=160, offsetX=55, offsetY=77, duration=0.0666667},
		[2]={u=1324, v=320, w=110, h=160, offsetX=55, offsetY=77, duration=0.0666667},
		[3]={u=1423, v=160, w=110, h=160, offsetX=55, offsetY=77, duration=0.0666667},
		[4]={u=1324, v=320, w=110, h=160, offsetX=55, offsetY=77, duration=0.0666667},
		[5]={u=1393, v=0, w=110, h=160, offsetX=55, offsetY=77, duration=0.0666667},
		scale=1
	},
	reactor3={
		[0]={u=1081, v=604, w=110, h=160, offsetX=56, offsetY=75, duration=0.0666667},
		[1]={u=1173, v=764, w=110, h=160, offsetX=56, offsetY=75, duration=0.0666667},
		[2]={u=1191, v=604, w=110, h=160, offsetX=56, offsetY=75, duration=0.0666667},
		[3]={u=1214, v=320, w=110, h=160, offsetX=56, offsetY=75, duration=0.0666667},
		[4]={u=1191, v=604, w=110, h=160, offsetX=56, offsetY=75, duration=0.0666667},
		[5]={u=1173, v=764, w=110, h=160, offsetX=56, offsetY=75, duration=0.0666667},
		scale=1
	},
	reactor4={
		[0]={u=641, v=628, w=110, h=160, offsetX=57, offsetY=76, duration=0.0666667},
		[1]={u=774, v=320, w=110, h=160, offsetX=57, offsetY=76, duration=0.0666667},
		[2]={u=866, v=160, w=110, h=160, offsetX=57, offsetY=76, duration=0.0666667},
		[3]={u=884, v=0, w=110, h=160, offsetX=57, offsetY=76, duration=0.0666667},
		[4]={u=866, v=160, w=110, h=160, offsetX=57, offsetY=76, duration=0.0666667},
		[5]={u=774, v=320, w=110, h=160, offsetX=57, offsetY=76, duration=0.0666667},
		scale=1
	},
	reactor5={
		[0]={u=531, v=648, w=110, h=160, offsetX=57, offsetY=80, duration=0.0666667},
		[1]={u=664, v=332, w=110, h=160, offsetX=57, offsetY=80, duration=0.0666667},
		[2]={u=754, v=160, w=110, h=160, offsetX=57, offsetY=80, duration=0.0666667},
		[3]={u=623, v=808, w=110, h=160, offsetX=57, offsetY=80, duration=0.0666667},
		[4]={u=754, v=160, w=110, h=160, offsetX=57, offsetY=80, duration=0.0666667},
		[5]={u=664, v=332, w=110, h=160, offsetX=57, offsetY=80, duration=0.0666667},
		scale=1
	},
	reactor6={
		[0]={u=1173, v=0, w=110, h=160, offsetX=57, offsetY=79, duration=0.0666667},
		[1]={u=994, v=320, w=110, h=160, offsetX=57, offsetY=79, duration=0.0666667},
		[2]={u=1086, v=160, w=110, h=160, offsetX=57, offsetY=79, duration=0.0666667},
		[3]={u=971, v=604, w=110, h=160, offsetX=57, offsetY=79, duration=0.0666667},
		[4]={u=1086, v=160, w=110, h=160, offsetX=57, offsetY=79, duration=0.0666667},
		[5]={u=994, v=320, w=110, h=160, offsetX=57, offsetY=79, duration=0.0666667},
		scale=1
	},
	reactor7={
		[0]={u=953, v=784, w=110, h=160, offsetX=57, offsetY=78, duration=0.0666667},
		[1]={u=884, v=320, w=110, h=160, offsetX=57, offsetY=78, duration=0.0666667},
		[2]={u=976, v=160, w=110, h=160, offsetX=57, offsetY=78, duration=0.0666667},
		[3]={u=1063, v=0, w=110, h=160, offsetX=57, offsetY=78, duration=0.0666667},
		[4]={u=976, v=160, w=110, h=160, offsetX=57, offsetY=78, duration=0.0666667},
		[5]={u=884, v=320, w=110, h=160, offsetX=57, offsetY=78, duration=0.0666667},
		scale=1
	},
	reactor8={
		[0]={u=554, v=335, w=110, h=160, offsetX=56, offsetY=79, duration=0.0666667},
		[1]={u=644, v=172, w=110, h=160, offsetX=56, offsetY=79, duration=0.0666667},
		[2]={u=664, v=0, w=110, h=160, offsetX=56, offsetY=79, duration=0.0666667},
		[3]={u=774, v=0, w=110, h=160, offsetX=56, offsetY=79, duration=0.0666667},
		[4]={u=664, v=0, w=110, h=160, offsetX=56, offsetY=79, duration=0.0666667},
		[5]={u=644, v=172, w=110, h=160, offsetX=56, offsetY=79, duration=0.0666667},
		scale=1
	},
	reactor9={
		[0]={u=1104, v=320, w=110, h=160, offsetX=56, offsetY=77, duration=0.0666667},
		[1]={u=1203, v=160, w=110, h=160, offsetX=56, offsetY=77, duration=0.0666667},
		[2]={u=1283, v=0, w=110, h=160, offsetX=56, offsetY=77, duration=0.0666667},
		[3]={u=1063, v=764, w=110, h=160, offsetX=56, offsetY=77, duration=0.0666667},
		[4]={u=1283, v=0, w=110, h=160, offsetX=56, offsetY=77, duration=0.0666667},
		[5]={u=1203, v=160, w=110, h=160, offsetX=56, offsetY=77, duration=0.0666667},
		scale=1
	},
	body_hit={
		[0]={u=0, v=1009, w=18, h=15, offsetX=0, offsetY=0, duration=0.0333333},
		scale=1
	},
	flesheater_hit={
		[0]={u=18, v=1009, w=10, h=13, offsetX=4, offsetY=7, duration=0.0333333},
		scale=1
	},
	spikey_hit={
		[0]={u=248, v=1012, w=13, h=11, offsetX=0, offsetY=0, duration=0.0333333},
		scale=1
	},
}
--data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
