-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."npc.sprite.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	characters_0000_Layer={
		[0]={u=0, v=0, w=12, h=28, offsetX=6, offsetY=28, duration=0.0333333},
		scale=1
	},
	characters_0001_Layer={
		[0]={u=0, v=30, w=16, h=28, offsetX=8, offsetY=28, duration=0.0333333},
		scale=1
	},
	characters_0002_Layer={
		[0]={u=14, v=0, w=12, h=28, offsetX=6, offsetY=28, duration=0.0333333},
		scale=1
	},
	characters_0003_Layer={
		[0]={u=18, v=30, w=12, h=28, offsetX=5, offsetY=28, duration=0.0333333},
		scale=1
	},
	characters_0004_Layer={
		[0]={u=28, v=0, w=12, h=28, offsetX=5, offsetY=28, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
